### PR TITLE
Add cronjob

### PR DESCRIPTION
**Pull request by Baptistee-B**

### CODE REVIEW

**Comment by Baptistee-B** [comment]
Not tested yet, but should work

**Comment by serge-tx** [comment]
thanks @BaptisteTamedia 

I've tried it out and get some syntax errors. you can check them with `helm lint .` locally.

Thinking about if it makes sense to wrap everything in the conditionals because it makes things more complicated than needed. Maybe it would be even better to create a `DND-IT/cron-helm-chart` repo instead. That's also what @mastertinner suggested when I was talking to him last week about this topic.

**Review by pierresteiner — COMMENTED** [review]
Instead of copy/pasting could you try to use that: https://helm.sh/docs/chart_template_guide/named_templates/ ?

**Comment by Baptistee-B** [comment]
Moved here : https://github.com/DND-IT/cron-helm-chart

**Pull request closed without merging**
